"use client";
/* eslint-disable @next/next/no-img-element */
import { BookOpen, Check, Copy, FileUp, LogOut, MessageCircle, Mic, MicOff, MonitorUp, PhoneOff, Send, ShieldCheck, SmilePlus, Sparkles, Users, Video, VideoOff, X } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import Whiteboard, { type Stroke } from "@/components/Whiteboard";
import { MeetingRoom, type Participant, type RoomEvent } from "@/lib/meeting-room";
import { WebRTCMesh } from "@/lib/webrtc-mesh";

type Message={id:string;name:string;text:string;time:string}; type SharedDoc={name:string;type:string;url:string};
const words=["learn","future","bright","skill","orbit","nova","class","spark"];
const roomCode=()=>`${words[Math.floor(Math.random()*words.length)]}-${words[Math.floor(Math.random()*words.length)]}-${Math.floor(100+Math.random()*900)}`;
const LOGO="https://www.skillvelop.com/_next/image?url=%2Fassets%2Fbrand%2Fskillvelop-wordmark.png&w=256&q=75";

function RemoteVideo({stream,name}:{stream:MediaStream;name:string}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current)ref.current.srcObject=stream},[stream]);return <article className="video-tile"><video ref={ref} autoPlay playsInline/><div className="tile-label">{name}</div></article>}

export default function Home(){
  const [meeting,setMeeting]=useState(false),[name,setName]=useState(""),[roomId,setRoomId]=useState(()=>typeof window==="undefined"?"":new URLSearchParams(location.search).get("room")||""),[limit,setLimit]=useState(()=>typeof window==="undefined"?2:Number(new URLSearchParams(location.search).get("size"))||2);
  const [isHost,setIsHost]=useState(false),[connected,setConnected]=useState(false),[people,setPeople]=useState<Participant[]>([]),[remoteStreams,setRemoteStreams]=useState<Map<string,MediaStream>>(new Map());
  const [micOn,setMicOn]=useState(true),[cameraOn,setCameraOn]=useState(true),[screen,setScreen]=useState(false),[panel,setPanel]=useState<"chat"|"people"|null>(null),[classroom,setClassroom]=useState(false);
  const [messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[reaction,setReaction]=useState(""),[strokes,setStrokes]=useState<Stroke[]>([]),[sharedDoc,setSharedDoc]=useState<SharedDoc|null>(null),[toast,setToast]=useState(""),[error,setError]=useState("");
  const localVideo=useRef<HTMLVideoElement>(null),localStream=useRef<MediaStream|null>(null),room=useRef<MeetingRoom|null>(null),mesh=useRef<WebRTCMesh|null>(null),fileChunks=useRef<Record<string,string[]>>({}),docBytes=useRef<{name:string;type:string;data:string}|null>(null),strokesRef=useRef<Stroke[]>([]),peopleRef=useRef<Participant[]>([]),hostRef=useRef(false);
  useEffect(()=>{strokesRef.current=strokes},[strokes]);useEffect(()=>{peopleRef.current=people},[people]);
  useEffect(()=>{if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});return()=>{void room.current?.disconnect();mesh.current?.close();localStream.current?.getTracks().forEach(t=>t.stop())}},[]);
  function notice(text:string){setToast(text);setTimeout(()=>setToast(""),2300)}
  async function broadcast(type:string,payload?:unknown,to?:string){room.current?.send(type,payload,to)}
  function applyEvent(event:RoomEvent){
    void mesh.current?.handle(event);
    const p=event.payload as Record<string,unknown>|undefined;
    if(event.type==="chat"&&p)setMessages(v=>[...v,p as unknown as Message]);
    if(event.type==="reaction"&&p){setReaction(String(p.emoji));setTimeout(()=>setReaction(""),1800)}
    if(event.type==="board"&&p)setStrokes((p.strokes as Stroke[])||[]);
    if(event.type==="host-mute"&&event.to===room.current?.clientId){localStream.current?.getAudioTracks().forEach(t=>t.enabled=false);setMicOn(false);notice("The host muted your microphone")}
    if(event.type==="host-remove"&&event.to===room.current?.clientId){notice("The host ended your participation");setTimeout(leave,900)}
    if(event.type==="request-state"&&hostRef.current){broadcast("board",{strokes:strokesRef.current},event.from);if(docBytes.current)sendDoc(docBytes.current,event.from)}
    if(event.type==="doc-start"&&p)fileChunks.current[String(p.id)]=[];
    if(event.type==="doc-chunk"&&p)fileChunks.current[String(p.id)]?.push(String(p.chunk));
    if(event.type==="doc-end"&&p){const id=String(p.id),data=fileChunks.current[id]?.join("")||"";delete fileChunks.current[id];const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:String(p.mime)}));setSharedDoc({name:String(p.name),type:String(p.mime),url});setClassroom(true)}
  }
  async function join(create=false){
    setError("");const id=roomId.trim()||roomCode(),host=create||!roomId.trim();setRoomId(id);setIsHost(host);hostRef.current=host;history.replaceState({},"",`?room=${encodeURIComponent(id)}&size=${limit}`);
    try{const media=await navigator.mediaDevices.getUserMedia({video:true,audio:true});localStream.current=media;setMeeting(true);setTimeout(()=>{if(localVideo.current)localVideo.current.srcObject=media},0);mesh.current=new WebRTCMesh(media,(t,p,to)=>broadcast(t,p,to),setRemoteStreams);
      const connection=new MeetingRoom(id,{name:name.trim()||"Guest",isHost:host,mic:true,camera:true},{onEvent:applyEvent,onPresence:(list)=>{setPeople(list);if(list.length>limit&&!list.some(p=>p.id===connection.clientId&&p.isHost)){setError(`This ${limit}-person room is full.`);void connection.disconnect()}},onStatus:setConnected});room.current=connection;await connection.connect();setMessages([{id:crypto.randomUUID(),name:"Skillvelop Meet",text:"Welcome! Media is encrypted and sent peer to peer.",time:"Now"}]);setTimeout(()=>broadcast("request-state"),800);
    }catch{setError("Camera and microphone permission is required to enter this meeting.")}
  }
  function toggle(kind:"audio"|"video"){const track=localStream.current?.getTracks().find(t=>t.kind===kind);if(track)track.enabled=!track.enabled;if(kind==="audio"){setMicOn(v=>!v);void room.current?.update({mic:!micOn})}else{setCameraOn(v=>!v);void room.current?.update({camera:!cameraOn})}}
  async function share(){try{if(screen){const cam=localStream.current?.getVideoTracks()[0];if(cam)await mesh.current?.replaceVideo(cam);if(localVideo.current)localVideo.current.srcObject=localStream.current;return setScreen(false)}const s=await navigator.mediaDevices.getDisplayMedia({video:true});const t=s.getVideoTracks()[0];await mesh.current?.replaceVideo(t);if(localVideo.current)localVideo.current.srcObject=s;setScreen(true);t.onended=()=>{setScreen(false);const cam=localStream.current?.getVideoTracks()[0];if(cam)void mesh.current?.replaceVideo(cam);if(localVideo.current)localVideo.current.srcObject=localStream.current}}catch{notice("Screen sharing cancelled")}}
  function chat(e:FormEvent){e.preventDefault();if(!draft.trim())return;const m={id:crypto.randomUUID(),name:name||"You",text:draft.trim(),time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})};setMessages(v=>[...v,m]);broadcast("chat",m);setDraft("")}
  function react(emoji:string){setReaction(emoji);broadcast("reaction",{emoji});setTimeout(()=>setReaction(""),1800)}
  function boardChange(next:Stroke[]){setStrokes(next);broadcast("board",{strokes:next})}
  async function upload(file:File){if(file.size>15*1024*1024)return notice("File must be smaller than 15 MB");const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]);r.onerror=reject;r.readAsDataURL(file)});docBytes.current={name:file.name,type:file.type,data};const url=URL.createObjectURL(file);setSharedDoc({name:file.name,type:file.type,url});setClassroom(true);sendDoc(docBytes.current)}
  function sendDoc(doc:{name:string;type:string;data:string},to?:string){const id=crypto.randomUUID(),step=60000;broadcast("doc-start",{id,name:doc.name,mime:doc.type},to);for(let i=0;i<doc.data.length;i+=step)setTimeout(()=>broadcast("doc-chunk",{id,chunk:doc.data.slice(i,i+step)},to),(i/step)*40);setTimeout(()=>broadcast("doc-end",{id,name:doc.name,mime:doc.type},to),(doc.data.length/step+1)*40)}
  async function copy(){await navigator.clipboard.writeText(location.href);notice("Guest link copied")}
  async function leave(){await room.current?.disconnect();room.current=null;mesh.current?.close();mesh.current=null;localStream.current?.getTracks().forEach(t=>t.stop());localStream.current=null;setMeeting(false);setClassroom(false);setPanel(null);history.replaceState({},"",location.pathname)}

  if(!meeting)return <main className="lobby-shell"><div className="particles">{Array.from({length:28},(_,i)=><i key={i}/>)}</div><nav className="topbar"><img className="wordmark" src={LOGO} alt="Skillvelop"/><div className="product-name">Meet <span>Beta</span></div><div className="open-source"><b/> Open-source WebRTC</div></nav><section className="lobby-grid"><div className="intro"><div className="eyebrow"><Sparkles size={14}/> AI-inspired collaborative classroom</div><h1>Teach beyond<br/><span>boundaries.</span></h1><p>Futuristic peer-to-peer classrooms with live video, shared whiteboards and collaborative teaching documents.</p><div className="trust-row"><span><ShieldCheck/>Encrypted media</span><span><BookOpen/>Teaching toolkit</span><span><MonitorUp/>Live collaboration</span></div></div><div className="join-card"><div className="card-heading"><span className="camera-orb"><Video/></span><div><h2>Start your classroom</h2><p>Choose a format, then invite learners.</p></div></div><label>Class format</label><div className="size-picker">{[{n:2,t:"1:1",s:"Tutor + 1"},{n:3,t:"1:2",s:"Tutor + 2"},{n:4,t:"1:3",s:"Tutor + 3"}].map(o=><button className={limit===o.n?"selected":""} key={o.n} onClick={()=>setLimit(o.n)}><span>{o.t}</span><small>{o.s}</small>{limit===o.n&&<Check/>}</button>)}</div><label>Your name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your display name"/><label>Meeting code <span>optional</span></label><input value={roomId} onChange={e=>setRoomId(e.target.value)} placeholder="Paste a code to join"/><button className="primary-action" onClick={()=>join(!roomId)}><Video/> {roomId?"Join classroom":"Create classroom"}</button>{error&&<p className="form-error">{error}</p>}<p className="fine-print">No account needed · Up to {limit} participants · Nothing is recorded</p></div></section></main>;

  return <main className="meeting-shell"><header className="meeting-header"><div className="meet-logo"><img src={LOGO} alt="Skillvelop"/><b>Meet</b></div><div className="room-info"><span className={connected?"live-dot":"wait-dot"}/><strong>{roomId}</strong><button onClick={copy}><Copy/></button></div><div className="secure"><ShieldCheck/> {limit===2?"1:1":limit===3?"1:2":"1:3"} classroom</div></header>
  {classroom?<section className="classroom-stage"><div className="classroom-bar"><div><BookOpen/><strong>{sharedDoc?.name||"Interactive whiteboard"}</strong></div><label className="upload"><FileUp/> Share PDF / PPT<input type="file" accept=".pdf,.ppt,.pptx,application/pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label><button onClick={()=>setClassroom(false)}><X/> Close board</button></div><Whiteboard strokes={strokes} onChange={boardChange} documentUrl={sharedDoc?.url} documentType={sharedDoc?.type}/><div className="mini-videos"><article><video ref={localVideo} autoPlay muted playsInline/>{reaction&&<b>{reaction}</b>}</article>{[...remoteStreams].map(([id,s])=><RemoteVideo key={id} stream={s} name={people.find(p=>p.id===id)?.name||"Learner"}/>)}</div></section>:<section className={`stage ${panel?"with-panel":""}`}><div className="video-grid"><article className="video-tile self-tile">{cameraOn?<video ref={localVideo} autoPlay muted playsInline/>:<div className="avatar">{(name||"Y")[0]}</div>}<div className="tile-label">{name||"You"} (Host){!micOn&&<MicOff/>}</div>{reaction&&<div className="floating-reaction">{reaction}</div>}</article>{[...remoteStreams].map(([id,s])=><RemoteVideo key={id} stream={s} name={people.find(p=>p.id===id)?.name||"Learner"}/>)}{Array.from({length:Math.max(0,limit-1-remoteStreams.size)},(_,i)=><article className="video-tile empty-tile" key={i}><div className="empty-rings"><Users/></div><p>Waiting for a learner</p><button onClick={copy}><Copy/> Copy invite link</button></article>)}</div>{panel&&<aside className="side-panel"><div className="panel-title"><div><h2>{panel==="chat"?"Class chat":"Participants"}</h2><p>{people.length} of {limit} connected</p></div><button onClick={()=>setPanel(null)}><X/></button></div>{panel==="chat"?<><div className="messages">{messages.map(m=><div className="message" key={m.id}><div><strong>{m.name}</strong><time>{m.time}</time></div><p>{m.text}</p></div>)}</div><form className="chat-box" onSubmit={chat}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Send a message"/><button><Send/></button></form></>:<div className="people-panel">{people.map(p=><div className="person" key={p.id}><span>{p.name[0]}</span><div><strong>{p.name}</strong><small>{p.isHost?"Host":"Learner"}</small></div>{isHost&&!p.isHost&&<><button title="Mute" onClick={()=>broadcast("host-mute",{},p.id)}><MicOff/></button><button title="Remove" onClick={()=>broadcast("host-remove",{},p.id)}><LogOut/></button></>}</div>)}</div>}</aside>}</section>}
  <footer className="control-dock"><div className="meeting-time">Skillvelop Meet <span/> {people.length}/{limit}</div><div className="main-controls"><button className={!micOn?"off":""} onClick={()=>toggle("audio")}>{micOn?<Mic/>:<MicOff/>}</button><button className={!cameraOn?"off":""} onClick={()=>toggle("video")}>{cameraOn?<Video/>:<VideoOff/>}</button><button className={screen?"active":""} onClick={share}><MonitorUp/></button><button className={classroom?"active":""} onClick={()=>setClassroom(v=>!v)}><BookOpen/></button><div className="reaction-menu"><button><SmilePlus/></button><div className="reaction-popover">{["👏","👍","🎉","❤️","😂","🤯"].map(e=><button key={e} onClick={()=>react(e)}>{e}</button>)}</div></div><button className="hangup" onClick={leave}><PhoneOff/></button></div><div className="secondary-controls"><button className={panel==="people"?"selected":""} onClick={()=>setPanel(panel==="people"?null:"people")}><Users/><span>{people.length}</span></button><button className={panel==="chat"?"selected":""} onClick={()=>setPanel(panel==="chat"?null:"chat")}><MessageCircle/></button></div></footer>{toast&&<div className="toast">{toast}</div>}{error&&<div className="error-toast">{error}</div>}</main>
}
