"use client";
import { Circle, Eraser, Highlighter, MousePointer2, Pencil, Redo2, Slash, Square, Trash2, Type, Undo2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";

export type Point = { x:number; y:number };
export type Stroke = { id:string; tool:string; color:string; size:number; points:Point[]; text?:string };
type Props = { strokes:Stroke[]; onChange:(strokes:Stroke[])=>void; documentUrl?:string; documentType?:string };

export default function Whiteboard({strokes,onChange,documentUrl,documentType}:Props){
  const canvasRef=useRef<HTMLCanvasElement>(null), [tool,setTool]=useState("pen"), [color,setColor]=useState("#7c5cff"), [size,setSize]=useState(4), [redo,setRedo]=useState<Stroke[]>([]), drawing=useRef<Stroke|null>(null);
  const render=useCallback(()=>{const c=canvasRef.current;if(!c)return;const dpr=devicePixelRatio||1,rect=c.getBoundingClientRect();if(c.width!==rect.width*dpr||c.height!==rect.height*dpr){c.width=rect.width*dpr;c.height=rect.height*dpr}const x=c.getContext("2d");if(!x)return;x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,rect.width,rect.height);for(const s of strokes){if(s.tool==="text"&&s.text){x.fillStyle=s.color;x.font=`${Math.max(16,s.size*4)}px sans-serif`;x.fillText(s.text,s.points[0].x*rect.width,s.points[0].y*rect.height);continue}const p=s.points.map(v=>({x:v.x*rect.width,y:v.y*rect.height}));if(!p.length)continue;x.beginPath();x.strokeStyle=s.tool==="eraser"?"#ffffff":s.color;x.globalAlpha=s.tool==="highlighter"?.35:1;x.lineWidth=s.tool==="highlighter"?s.size*4:s.size;x.lineCap="round";x.lineJoin="round";if(s.tool==="rect"&&p[1])x.strokeRect(p[0].x,p[0].y,p[1].x-p[0].x,p[1].y-p[0].y);else if(s.tool==="circle"&&p[1]){x.ellipse((p[0].x+p[1].x)/2,(p[0].y+p[1].y)/2,Math.abs(p[1].x-p[0].x)/2,Math.abs(p[1].y-p[0].y)/2,0,0,Math.PI*2);x.stroke()}else{p.forEach((v,i)=>i?x.lineTo(v.x,v.y):x.moveTo(v.x,v.y));x.stroke()}x.globalAlpha=1}},[strokes]);
  useEffect(()=>{render();const observer=new ResizeObserver(render);if(canvasRef.current)observer.observe(canvasRef.current);return()=>observer.disconnect()},[render]);
  const point=(e:React.PointerEvent)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}};
  function down(e:React.PointerEvent){if(tool==="pointer")return;if(tool==="text"){const text=prompt("Type on the board");if(text)onChange([...strokes,{id:crypto.randomUUID(),tool,color,size,points:[point(e)],text}]);return}e.currentTarget.setPointerCapture(e.pointerId);drawing.current={id:crypto.randomUUID(),tool,color,size,points:[point(e)]};onChange([...strokes,drawing.current]);setRedo([])}
  function move(e:React.PointerEvent){if(!drawing.current)return;const p=point(e);if(["rect","circle","line"].includes(tool))drawing.current.points=[drawing.current.points[0],p];else drawing.current.points.push(p);onChange([...strokes.filter(s=>s.id!==drawing.current?.id),{...drawing.current,points:[...drawing.current.points]}])}
  function up(){drawing.current=null}
  const tools=[{id:"pointer",icon:MousePointer2},{id:"pen",icon:Pencil},{id:"highlighter",icon:Highlighter},{id:"eraser",icon:Eraser},{id:"line",icon:Slash},{id:"rect",icon:Square},{id:"circle",icon:Circle},{id:"text",icon:Type}];
  return <div className="whiteboard"><div className="board-tools">{tools.map(t=><button key={t.id} className={tool===t.id?"chosen":""} onClick={()=>setTool(t.id)} title={t.id}><t.icon/></button>)}<i/><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><input aria-label="Brush size" type="range" min="2" max="16" value={size} onChange={e=>setSize(+e.target.value)}/><i/><button title="Undo" onClick={()=>{const last=strokes.at(-1);if(last){setRedo(r=>[...r,last]);onChange(strokes.slice(0,-1))}}}><Undo2/></button><button title="Redo" onClick={()=>{const last=redo.at(-1);if(last){onChange([...strokes,last]);setRedo(redo.slice(0,-1))}}}><Redo2/></button><button title="Clear" onClick={()=>onChange([])}><Trash2/></button></div><div className="board-page">{documentUrl&&(documentType==="application/pdf"?<iframe src={`${documentUrl}#toolbar=0`} title="Shared PDF"/>:<div className="ppt-fallback"><strong>Shared presentation</strong><p>Annotate this shared workspace. Export PPT/PPTX to PDF for exact slide rendering.</p><a href={documentUrl} download>Open original file</a></div>)}<canvas ref={canvasRef} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}/></div></div>
}
